fun main() {
    println("Hello, Android!")
    println("Hello, Android!")
    println("Hello, Sabire!")
    println("1")
    println("2")
    println("3")
    println("I'm")
    println("learning")
    println("Kotlin!")
    println("Monday")
    println("Tuesday")
    println("Wednesday")
    println("Thursday")
    println("Friday")
    println("Tomorrow is rainy")
    println("There is a chance of snow")
    println("Cloudy")
    println("Partly Cloudy")
    println("Windy")
    println("How's the weather today?")
}
